---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytaskGo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mytaskGo
  template:
    metadata:
      labels:
        app: mytaskGo
    spec:
      containers:
      - name: mytaskGo
        image: joelsipayung/cicdjenkinskubego:latest
        imagePullPolicy: Always
        

---
apiVersion: v1
kind: Service
metadata:
  name: mytaskGo
spec:
  ports:
  - nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mytaskGo
  type: NodePort
