apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytaskgo
  labels:
    app: mytaskgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytaskgo
  template:
    metadata:
      labels:
        app: mytaskgo
    spec:
      containers:
        - name: mytaskgo
          image: joelsipayung/cicdjenkinskubego:latest
          imagePullPolicy: Always
          ports:
            - name: http-ports
              containerPort: 80
      imagePullSecrets:
	      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: mytaskgo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http-ports
  selector:
    app: mytaskgo
